// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pressford.News.Data;

namespace Pressford.News.Data.Migrations
{
    [DbContext(typeof(PressfordNewsContext))]
    [Migration("20200930124656_Changed Entity name from AuthorName to Author")]
    partial class ChangedEntitynamefromAuthorNametoAuthor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pressford.News.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Pressford.News.Entities.ArticleLikes", b =>
                {
                    b.Property<int>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LikeId");

                    b.ToTable("ArticleLikes");
                });

            modelBuilder.Entity("Pressford.News.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "w.Pressford@pressford.com",
                            FirstName = "W",
                            LastName = "Pressford"
                        },
                        new
                        {
                            Id = 2,
                            Email = "adminUser@pressford.com",
                            FirstName = "Admin",
                            LastName = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "normalUser@pressford.com",
                            FirstName = "Normal",
                            LastName = "User"
                        });
                });

            modelBuilder.Entity("Pressford.News.Entities.UserLogin", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("UserLogin");

                    b.HasData(
                        new
                        {
                            Username = "w.Pressford@pressford.com",
                            Password = "admin",
                            Role = "Publisher"
                        },
                        new
                        {
                            Username = "adminUser@pressford.com",
                            Password = "admin",
                            Role = "Publisher"
                        },
                        new
                        {
                            Username = "normalUser@pressford.com",
                            Password = "user",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("Pressford.News.Entities.UserLogin", b =>
                {
                    b.HasOne("Pressford.News.Entities.User", "User")
                        .WithOne("LoginInfo")
                        .HasForeignKey("Pressford.News.Entities.UserLogin", "Username")
                        .HasPrincipalKey("Pressford.News.Entities.User", "Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
